### ISSUE TITLE
test_dir file path dataset content

### ISSUE THREAD

**Issue by SedaBalta** [anuragkj/Face-Anti-Spoofing_using_CNN#2]
Hello, when I examined your output.xlsx files in detail, I saw that the data in the train_test column was only "train". However, in the result_analysis.ipynb file, the same column also contains the "test" tag. What kind of path should be followed to obtain the train and test labels here? Should images be given as classes in the test_dir path?

**Comment by anuragkj** [comment]
Hi!
The column train_test in output.xlsx depends on the label given when generating (see line 385 in ensemble.py). This does not have any role in the code, just for personal reference.
The entire data (present in output.xlsx) is then split into train and test in the result analysis.ipynb in a 80-20 split.
To obtain the labels in output.xlsx you have to run the ensemble.py python script. The main function is where you put all parameters like the input folder with all images and the path to your models(the path are harcoded, so you have to update for your PC).
The output labels are stored in the path given by variable "output_excel_path".
